language: fr
lives:
  max: -1
  min: 1
firework:
  isEnable: true
  count: 10
broadcast:
  comeJoin:
    enable: false
    number: 0
times:
  wait: 30
  jump: 15
rewards:
  win: 0
  lose: 0
block:
  - "STONE:0"
  - "STONE:1"
  - "STONE:2"
  - "STONE:3"
  - "STONE:4"
  - "STONE:5"
  - "GRASS:0"
  - "DIRT:0"
  - "COBBLESTONE:0"
  - "WOOD:0"
  - "WOOD:1"
  - "WOOD:2"
  - "WOOD:3"
  - "WOOD:4"
  - "WOOD:5"
  - "SAND:0"
  - "GRAVEL:0"
  - "GOLD_ORE:0"
  - "IRON_ORE:0"
  - "COAL_ORE:0"
  - "LOG:0"
  - "LOG:1"
  - "LOG:2"
  - "LOG:3"
  - "GLASS:0"
  - "LAPIS_ORE:0"
  - "LAPIS_BLOCK:0"
  - "DISPENSER:0"
  - "SANDSTONE:0"
  - "NOTE_BLOCK:0"
  - "WOOL:0"
  - "WOOL:1"
  - "WOOL:2"
  - "WOOL:3"
  - "WOOL:4"
  - "WOOL:5"
  - "WOOL:6"
  - "WOOL:7"
  - "WOOL:8"
  - "WOOL:9"
  - "WOOL:10"
  - "WOOL:11"
  - "WOOL:12"
  - "WOOL:13"
  - "WOOL:14"
  - "GOLD_BLOCK:0"
  - "IRON_BLOCK:0"
  - "BRICK:0"
  - "BOOKSHELF:0"
  - "MOSSY_COBBLESTONE:0"
  - "OBSIDIAN:0"
  - "DIAMOND_ORE:0"
  - "DIAMOND_BLOCK:0"
  - "WORKBENCH:0"
  - "SOIL:0"
  - "REDSTONE_ORE:0"
  - "GLOWING_REDSTONE_ORE:0"
  - "ICE:0"
  - "SNOW_BLOCK:0"
  - "CLAY:0"
  - "JUKEBOX:0"
  - "PUMPKIN:0"
  - "NETHERRACK:0"
  - "SOUL_SAND:0"
  - "GLOWSTONE:0"
  - "JACK_O_LANTERN:0"
  - "STAINED_GLASS:0"
  - "STAINED_GLASS:1"
  - "STAINED_GLASS:2"
  - "STAINED_GLASS:3"
  - "STAINED_GLASS:4"
  - "STAINED_GLASS:5"
  - "STAINED_GLASS:6"
  - "STAINED_GLASS:7"
  - "STAINED_GLASS:8"
  - "STAINED_GLASS:9"
  - "STAINED_GLASS:10"
  - "STAINED_GLASS:11"
  - "STAINED_GLASS:12"
  - "STAINED_GLASS:13"
  - "STAINED_GLASS:14"
  - "SMOOTH_BRICK:0"
  - "HUGE_MUSHROOM_1:0"
  - "HUGE_MUSHROOM_2:0"
  - "MELON_BLOCK:0"
  - "MYCEL:0"
  - "NETHER_BRICK:0"
  - "ENCHANTMENT_TABLE:0"
  - "ENDER_PORTAL_FRAME:0"
  - "ENDER_STONE:0"
  - "REDSTONE_LAMP_OFF:0"
  - "REDSTONE_LAMP_ON:0"
  - "BEACON:0"
  - "REDSTONE_BLOCK:0"
  - "QUARTZ_ORE:0"
  - "QUARTZ_BLOCK:0"
  - "DROPPER:0"
  - "STAINED_CLAY:0"
  - "STAINED_CLAY:1"
  - "STAINED_CLAY:2"
  - "STAINED_CLAY:3"
  - "STAINED_CLAY:4"
  - "STAINED_CLAY:5"
  - "STAINED_CLAY:6"
  - "STAINED_CLAY:7"
  - "STAINED_CLAY:8"
  - "STAINED_CLAY:9"
  - "STAINED_CLAY:10"
  - "STAINED_CLAY:11"
  - "STAINED_CLAY:12"
  - "STAINED_CLAY:13"
  - "STAINED_CLAY:14"
  - "LOG_2:0"
  - "LOG_2:1"
  - "PRISMARINE:0"
  - "SEA_LANTERN:0"
  - "HAY_BLOCK:0"
  - "HARD_CLAY:0"
  - "COAL_BLOCK:0"
  - "PACKED_ICE:0"
  - "RED_SANDSTONE:0"
  - "PURPUR_BLOCK:0"
  - "PURPUR_PILLAR:0"
  - "END_BRICKS:0"
  - "GRASS_PATH:0"
  - "FROSTED_ICE:0"
  - "MAGMA:0"
  - "NETHER_WART_BLOCK:0"
  - "RED_NETHER_BRICK:0"
  - "BONE_BLOCK:0"
  - "OBSERVER:0"
  - "WHITE_SHULKER_BOX:0"
  - "ORANGE_SHULKER_BOX:0"
  - "MAGENTA_SHULKER_BOX:0"
  - "LIGHT_BLUE_SHULKER_BOX:0"
  - "YELLOW_SHULKER_BOX:0"
  - "LIME_SHULKER_BOX:0"
  - "PINK_SHULKER_BOX:0"
  - "GRAY_SHULKER_BOX:0"
  - "SILVER_SHULKER_BOX:0"
  - "CYAN_SHULKER_BOX:0"
  - "PURPLE_SHULKER_BOX:0"
  - "BLUE_SHULKER_BOX:0"
  - "BROWN_SHULKER_BOX:0"
  - "GREEN_SHULKER_BOX:0"
  - "RED_SHULKER_BOX:0"
  - "BLACK_SHULKER_BOX:0"
  - "WHITE_GLAZED_TERRACOTTA:0"
  - "ORANGE_GLAZED_TERRACOTTA:0"
  - "MAGENTA_GLAZED_TERRACOTTA:0"
  - "LIGHT_BLUE_GLAZED_TERRACOTTA:0"
  - "YELLOW_GLAZED_TERRACOTTA:0"
  - "LIME_GLAZED_TERRACOTTA:0"
  - "PINK_GLAZED_TERRACOTTA:0"
  - "GRAY_GLAZED_TERRACOTTA:0"
  - "SILVER_GLAZED_TERRACOTTA:0"
  - "CYAN_GLAZED_TERRACOTTA:0"
  - "PURPLE_GLAZED_TERRACOTTA:0"
  - "BLUE_GLAZED_TERRACOTTA:0"
  - "BROWN_GLAZED_TERRACOTTA:0"
  - "GREEN_GLAZED_TERRACOTTA:0"
  - "RED_GLAZED_TERRACOTTA:0"
  - "BLACK_GLAZED_TERRACOTTA:0"
  - "CONCRETE:0"
  - "CONCRETE:1"
  - "CONCRETE:2"
  - "CONCRETE:3"
  - "CONCRETE:4"
  - "CONCRETE:5"
  - "CONCRETE:6"
  - "CONCRETE:7"
  - "CONCRETE:8"
  - "CONCRETE:9"
  - "CONCRETE:10"
  - "CONCRETE:11"
  - "CONCRETE:12"
  - "CONCRETE:13"
  - "CONCRETE:14"
  - "CONCRETE_POWDER:0"
  - "CONCRETE_POWDER:1"
  - "CONCRETE_POWDER:2"
  - "CONCRETE_POWDER:3"
  - "CONCRETE_POWDER:4"
  - "CONCRETE_POWDER:5"
  - "CONCRETE_POWDER:6"
  - "CONCRETE_POWDER:7"
  - "CONCRETE_POWDER:8"
  - "CONCRETE_POWDER:9"
  - "CONCRETE_POWDER:10"
  - "CONCRETE_POWDER:11"
  - "CONCRETE_POWDER:12"
  - "CONCRETE_POWDER:13"
  - "CONCRETE_POWDER:14"